# Generated by Django 4.2.5 on 2023-09-30 04:20

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('slug', models.SlugField()),
                ('navbar_main', models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default=1)),
                ('navbar_footer', models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0)),
                ('navbar_secondary', models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0)),
                ('navbar_sidebar', models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0)),
                ('active', models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default=1)),
                ('header_image', models.ImageField(blank=True, upload_to='images/')),
                ('seo', models.TextField(default='null', max_length=200)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(default='null')),
            ],
        ),
        migrations.CreateModel(
            name='SiteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('status', models.IntegerField(choices=[(0, 'Maintenance'), (1, 'Production')], default=0)),
                ('title', models.CharField(blank=True, max_length=60, null=True)),
                ('slug', models.SlugField(blank=True, max_length=60, null=True)),
                ('tagline', models.CharField(blank=True, max_length=75, null=True)),
                ('logo', models.ImageField(blank=True, upload_to='images/website')),
                ('contact', models.CharField(blank=True, max_length=35, null=True)),
                ('email', models.CharField(blank=True, max_length=35, null=True)),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('website', models.CharField(blank=True, max_length=35, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('address2', models.CharField(blank=True, max_length=30, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('state', models.CharField(blank=True, max_length=30, null=True)),
                ('zip', models.CharField(blank=True, max_length=10, null=True)),
                ('google_map', models.CharField(blank=True, max_length=200, null=True)),
                ('seo_description', models.CharField(blank=True, max_length=200, null=True)),
                ('bio_title', models.CharField(blank=True, max_length=60, null=True)),
                ('bio_slug', models.SlugField(blank=True, max_length=60, null=True)),
                ('bio_tagline', models.CharField(blank=True, max_length=75, null=True)),
                ('bio_header', models.CharField(blank=True, max_length=75, null=True)),
                ('bio', ckeditor_uploader.fields.RichTextUploadingField()),
                ('facebook', models.CharField(blank=True, max_length=30, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=30, null=True)),
                ('twitter', models.CharField(blank=True, max_length=30, null=True)),
                ('instagram', models.CharField(blank=True, max_length=30, null=True)),
                ('tiktok', models.CharField(blank=True, max_length=30, null=True)),
                ('google_profile', models.CharField(blank=True, max_length=200, null=True)),
                ('youtube', models.CharField(blank=True, max_length=200, null=True)),
                ('cashapp', models.CharField(blank=True, max_length=30, null=True)),
                ('venmo', models.CharField(blank=True, max_length=30, null=True)),
                ('github', models.CharField(blank=True, max_length=30, null=True)),
                ('discord', models.CharField(blank=True, max_length=30, null=True)),
                ('linktree', models.CharField(blank=True, max_length=30, null=True)),
                ('facetime', models.CharField(blank=True, max_length=30, null=True)),
                ('microsoft', models.CharField(blank=True, max_length=30, null=True)),
                ('twitch', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'Site Profile',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('is_about', models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('header_image', models.ImageField(blank=True, upload_to='posts/header_images')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('seo_teaser', models.TextField(default='NULL', max_length=200)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(default='1', to='website.category')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
