# Generated by Django 4.2.5 on 2023-10-01 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='copyright',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
